import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from './../components/Navbar/Navbar';
import AuthProvider from "./context/AuthProvider";
import { Toaster } from "react-hot-toast";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-commerce Website",
  description: "Generated by create next app",
  icons: { icon: '/810663_file.png'   }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {




  return (

    <html lang="en" >
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

<Toaster position="top-center" reverseOrder={false}  />

      <AuthProvider>
          <div className="navb sticky top-0 z-50 bg-[#FFFFFF]">
          
        <Navbar />

        </div>

        
        {children}
      
      </AuthProvider>

      </body>
    </html>
  );
}
